
POST  http://localhost:8000/accounts/register
Content-Type: application/json

{
    "username": "admin2",
    "firstname": "Daniel",
    "lastname": "Brooks",
    "email": "steve.lynch47@ethereal.email",
    "password": "admin",
    "passwordConfirm": "admin"
}

###
POST  http://localhost:8000/accounts/verify-email
Content-Type: application/json

{
  "token": "af6df251538f5a0215af9c96b10db2d8e958dc937f98ca17ea0886271288f255d6666323902d39b0"
}

###
POST  http://localhost:8000/accounts/authenticate
Content-Type: application/json

{
  "email": "admin.mail@mail.com",
  "password": "admin"
}

  # "email": "steve.lynch47@ethereal.email",
  # "email": "admin.mail@mail.com",
###
POST  http://localhost:8000/accounts/refresh-token
###

POST  http://localhost:8000/accounts/revoke-token
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjI2MTQ5ZjExMzM2ODQxN2Q3ZDcwNWQiLCJpZCI6IjYyMjYxNDlmMTEzMzY4NDE3ZDdkNzA1ZCIsImlhdCI6MTY0NjY2NjAwMywiZXhwIjoxNjQ2NjY2OTAzfQ.9jjiGoxXIZryHv_zkGCAX0JIzIcKArw6P27NetUn7EE

###
POST  http://localhost:8000/accounts/forgot-password
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjI2MTQ5ZjExMzM2ODQxN2Q3ZDcwNWQiLCJpZCI6IjYyMjYxNDlmMTEzMzY4NDE3ZDdkNzA1ZCIsImlhdCI6MTY0NjY2NjgzOCwiZXhwIjoxNjQ2NjY3NzM4fQ.LB42dQl7pkjd-yrtvMniX_VCMSbTCNSjq0PccD5g43M

{
  "email": "steve.lynch47@ethereal.email"
}

###
POST  http://localhost:8000/accounts/reset-password
Content-Type: application/json

{
  "token": "a99b918e2345d8a32ded4f530ccf4aada87acb6f79029b336b19d835ecba303d0ff236c554f412d9",
  "password": "admin2",
  "passwordConfirm": "admin2"
}

###
GET  http://localhost:8000/accounts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjI2MTQ5ZjExMzM2ODQxN2Q3ZDcwNWQiLCJpZCI6IjYyMjYxNDlmMTEzMzY4NDE3ZDdkNzA1ZCIsImlhdCI6MTY0NjY2ODMwMiwiZXhwIjoxNjQ2NjY5MjAyfQ.iQcfmzHZc1H4RVQnF2dTq09NLUZ3aolSMYfDWOfSDpE
###

GET  http://localhost:8000/accounts/6226149f113368417d7d705f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjI1ZmJjZGQ0MDkwYmIwYjMyNGU4ZTgiLCJpZCI6IjYyMjVmYmNkZDQwOTBiYjBiMzI0ZThlOCIsImlhdCI6MTY0NjY2ODYxMSwiZXhwIjoxNjQ2NjY5NTExfQ.RUqj_tcVdeAeQ-KXeHmNcT-G9ULrHD8itf2FdTtoSFY


# "id": "6226149f113368417d7d705d"
# "id": "6225fbcdd4090bb0b324e8e8"