
POST  http://localhost:8000/accounts/register
Content-Type: application/json

{
    "username": "admin2",
    "firstname": "Daniel",
    "lastname": "Brooks",
    "email": "steve.lynch47@ethereal.email",
    "password": "admin",
    "passwordConfirmed": "admin"
}

###
POST  http://localhost:8000/accounts/verify-email
Content-Type: application/json

{
  "token": "af6df251538f5a0215af9c96b10db2d8e958dc937f98ca17ea0886271288f255d6666323902d39b0"
}

###
POST  http://localhost:8000/accounts/authenticate
Content-Type: application/json

{
  "email": "admin.mail@mail.com",
  "password": "admin"
}

###
POST  http://localhost:8000/accounts/refresh-token
###

POST  http://localhost:8000/accounts/revoke-token
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjI1ZmJjZGQ0MDkwYmIwYjMyNGU4ZTgiLCJpZCI6IjYyMjVmYmNkZDQwOTBiYjBiMzI0ZThlOCIsImlhdCI6MTY0NjY2NDA4MywiZXhwIjoxNjQ2NjY0OTgzfQ.7YF3oOGiGzNdRs9FFapX2qvhXWkKkRBEZSfpxo2dPHU